tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
cask "java"
brew "autoenv"
brew "aws-shell"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "checkbashisms"
brew "colordiff"
brew "diff-so-fancy"
brew "direnv"
brew "dockutil"
brew "elm"
brew "fd"
brew "lame"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "git"
brew "groovy"
brew "highlight"
brew "httpie"
brew "jq"
brew "less"
brew "lesspipe"
brew "mas"
brew "ngrep"
brew "nvm"
brew "osxutils"
brew "p7zip"
brew "pidof"
brew "ripgrep"
brew "ruby"
brew "shellcheck"
brew "the_silver_searcher"
brew "tmate"
brew "tmux"
brew "unrar"
brew "watch"
brew "watchman"
brew "wdiff"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "z"
cask "1password6"
cask "acorn"
cask "alfred"
cask "bartender"
cask "brave-browser"
cask "cyberghost"
cask "dash3"
cask "expressvpn"
cask "firefox"
cask "font-fira-code"
cask "franz"
cask "gfxcardstatus"
cask "gimp"
cask "google-chrome"
cask "grammarly"
cask "hyper"
cask "istat-menus5"
cask "iterm2"
cask "keepingyouawake"
cask "keybase"
cask "mpv"
cask "muzzle"
cask "qutebrowser"
cask "safari-technology-preview"
cask "skitch"
cask "skype-for-business"
cask "spectacle"
cask "spotify"
cask "textmate"
cask "virtualbox"
cask "visual-studio-code"
cask "whatsapp"
mas "Bear", id: 1091189122
mas "GIF Brewery 3", id: 1081413713
mas "iA Writer", id: 775737590
mas "Ka-Block!", id: 1335413823
mas "Keynote", id: 409183694
mas "Microsoft Remote Desktop", id: 1295203466
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Simplenote", id: 692867256
mas "Spark", id: 1176895641
mas "Wunderlist", id: 410628904
mas "Xcode", id: 497799835
