tap "caskroom/cask"
tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
brew "autoenv"
brew "bash-completion"
brew "checkbashisms"
brew "dockutil"
brew "git"
brew "groovy"
brew "httpie"
brew "jq"
brew "less"
brew "mas"
brew "nvm"
brew "osxutils"
brew "pass"
brew "postgresql", restart_service: true
brew "ripgrep"
brew "ruby"
brew "shellcheck"
brew "the_silver_searcher"
brew "watch"
brew "yarn"
brew "youtube-dl"
brew "z"
cask "1password"
cask "acorn"
cask "alfred"
cask "bartender"
cask "ccmenu"
cask "dash3"
cask "docker"
cask "dropbox"
cask "firefox"
cask "gfxcardstatus"
cask "gimp"
cask "google-chrome-beta"
cask "gpgtools-beta"
cask "hyper"
cask "intel-haxm"
cask "intellij-idea"
cask "istat-menus"
cask "iterm2"
cask "java"
cask "keepingyouawake"
cask "mpv"
cask "muzzle"
cask "owncloud"
cask "rocket"
cask "screenhero"
cask "skitch"
cask "slack"
cask "spectacle"
cask "spotify"
cask "textmate"
cask "tripmode"
cask "visual-studio-code"
mas "GIF Brewery 3", id: 1081413713
mas "iA Writer", id: 775737590
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Simplenote", id: 692867256
mas "Xcode", id: 497799835
