tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
brew 'autoenv'
brew 'bash-completion'
brew 'git'
brew 'httpie'
brew 'mas'
brew 'nvm'
brew 'osxutils'
brew 'postgresql', restart_service: true
brew 'ruby'
brew 'yarn'
brew 'youtube-dl'
cask '1password'
cask 'alfred'
cask 'dash3'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome-beta'
cask 'gpgtools-beta'
cask 'intellij-idea'
cask 'iterm2'
cask 'java'
cask 'mpv'
cask 'owncloud'
cask 'screenhero'
cask 'slack'
cask 'textmate'
cask 'tripmode'
cask 'visual-studio-code'
mas 'GIF Brewery 3', id: 1081413713
mas 'iA Writer', id: 775737590
